import React from "react";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Menu } from "@/src/app/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next JS Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const menuConfig = [
    { title: "Home", link: "/" },
    { title: "Test Dynamic URL", link: "/test-dynamic-url" },
    { title: "Contacts", link: "/contacts" },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu data={menuConfig} />
        {children}
      </body>
    </html>
  );
}
